name: License Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Cancel already running jobs
concurrency:
  group: license_check_${{ github.head_ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  license_check:
    runs-on: ubuntu-22.04
    name: License Check
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo deny
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny@0.14.24
      - run: cargo-deny check licenses
