---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  publish-crates-io:
    name: "Publish to crates.io"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        run: |
          cd tokio-bin-process
          cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
